name: SmartLoan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  dio: ^5.3.3
  shared_preferences: ^2.0.7
  connectivity_plus: ^5.0.1
  retry: ^3.1.2
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  android_id: ^0.3.6
  fluttertoast: ^8.2.4
  webview_flutter: 4.4.1
  permission_handler: 10.0.2
  url_launcher: ^6.1.0
  # å®‰è£…æ¥æº
  install_referrer: ^1.2.1

  appsflyer_sdk: ^6.12.2

  sdk_credit:
    path: plugins/sdk_credit
  liveness_plugin:
    path: plugins/liveness_plugin
  image_picker: ^1.0.4
  get_it: ^7.6.4
  flutter_animated_dialog: ^2.0.1
  encrypt: ^5.0.3
  flutter_image_compress: 2.1.0
  image: 4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/



